### ISSUE TITLE
nat commands are missing

### ISSUE THREAD

**Issue by Teibayo** [devgiants/livebox#5]
Hello,

Thank you for the good work, it is pretty hard to find any tool or documentation to administrate your livebox through cli or an api.
I installed your tool which works fine on a livebox 5 as well but i don't see any nat commands ("Command "nat" is not defined." / "There are no commands defined in the "nat" namespace.").
I see the wifi and wan commands but the ones I really need are the nat ones :) did I miss something ?

Thanks!

**Comment by devgiants** [comment]
Hi there,

Thanks for positive feebacks on this work. Glad it can help you :). 
The problems comes with the PHAR archive : documentation was not up to date ([fixed](https://github.com/devgiants/livebox/tree/1.5.3)) and it is not the way to go anymore. Plea use direct entrypoint invokation.

_Sidenote : I dropped the PHAR away due to the lack of maintenance around generating packages. If you have time and want to contribute, feel free to submit MR with PHAR stubbing pimped :)_

**Comment by Teibayo** [comment]
Hello,

Thanks for the answer, however using the direct entrypoint invokation after cloning I always get an error due to the fact that the livebox script require the file /vendor/autoload.php that doesn't exist on the repository. 
Do I miss something ? It seems the method to install doesn't work unfortunately

Thanks

**Comment by devgiants** [comment]
Yes, it is normal. Actually, this is a PHP CLI application using `composer`, and you need to execute `composer install` for retrieving all needed components.

**Comment by Teibayo** [comment]
Indeed that works perfectly ! 
Sorry I'm not used to php and didn't know composer to install dependencies but it seems logical now !
Maybe you should add this in the documentation for novice people ?
Thanks again 👍
