### ISSUE TITLE
autoload.php not found

### ISSUE THREAD

**Issue by paucazou** [devgiants/livebox#7]
Hi, 
thanks for this interesting library. I've just cloned the repo but canno't launch the app:
`PHP Warning:  require(/save/scripts/livebox/livebox/bin/../vendor/autoload.php): Failed to open stream: No such file or directory in /save/scripts/livebox/livebox/bin/livebox on line 10
PHP Fatal error:  Uncaught Error: Failed opening required '/save/scripts/livebox/livebox/bin/../vendor/autoload.php' (include_path='.:/usr/share/php') in /save/scripts/livebox/livebox/bin/livebox:10
Stack trace:
#0 {main}
  thrown in /save/scripts/livebox/livebox/bin/livebox on line 10
`

Are there any dependency I haven't yet installed? I can't find any 'vendor' directory.
Thanks!

**Comment by devgiants** [comment]
Hello,
Your not the first one asking me this, my installation steps weren't detailled enough. This is fixed with [this commit](https://github.com/devgiants/livebox/commit/ec3f1594dd045897a537e6bb3abc7e48c3d8f851).

You must install dependencies first, which will create `autoload.php` file and `vendor` directory, for which you rightly pointed out the lack.

**Comment by paucazou** [comment]
Thank you. Unfortunately, I've found a new bug just after launching 'composer install' ( a problem with PHP version).

**Comment by raphraph** [comment]
Hi @devgiants, I have the same problem I suppose, I get the following error when trying to run `composer install` :

```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - kriswallsmith/buzz is locked to version v0.15.2 and an update of this package was not requested.
    - kriswallsmith/buzz v0.15.2 requires php ^5.3.3 || ^7.0 -> your php version (8.1.2) does not satisfy that requirement.
```
Is it possible to use an updated `kriswallsmith/buzz` version ? Latest version (1.2.1) supports php8 but changing this manually in the `composer.json` leads to a conflict with the `composer.lock` (of course)...

I don't know how this works exactly so any hints or help on how to do that would be greatly appreciated ! Thanks.

**Comment by devgiants** [comment]
Hello @raphraph ,

This is because you're using PHP 8. I didn't adapt the dependencies requirements yet. That being said, this should reasonnably working once done (I don't have enough time for this right now, sorry).

If you feel comfortable enough with, you can submit PR I will review and accept it with pleasure. Docker stack embedded can be a good start as well.

Thanks,
